{% set name = "segment-anything-hq" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/segment-anything-hq-{{ version }}.tar.gz
  sha256: fab190efcd9bcf02a52cc13a628b40745aa5aeb75da1ce9e9b919b13a0206836

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pytorch >=1.7
    - torchvision >=0.8
    - timm

test:
  imports:
    - segment_anything_hq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SysCV/sam-hq
  summary: Official Python package for Segment Anything in High Quality (https://arxiv.org/abs/2306.01567)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
